### ISSUE TITLE
Error: "No module named 'packaging'"

### ISSUE THREAD

**Issue by ericmclachlan** [google/pygtrie#32]
Hi Googlers

I noticed an error when building my solution today. We use pygtrie in our solution and it seems that the crash we experienced is related to the release of `pygtrie 2.4.0`.

This is corroborated by:
- the error message; 
- the timing of the release of pygtrie 2.4.0 ([yesterday](https://pypi.org/project/pygtrie/#history)), and
- Reverting to pygtrie 2.3.3 seems to resolve the problem.

The full error description can be found below:

```
Collecting pygtrie
  Downloading pygtrie-2.4.0.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p_3v3rdq/pygtrie/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p_3v3rdq/pygtrie/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yevdgn7f
         cwd: /tmp/pip-install-p_3v3rdq/pygtrie/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p_3v3rdq/pygtrie/setup.py", line 5, in <module>
        import packaging.version
    ModuleNotFoundError: No module named 'packaging'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mina86** [comment]
This should now be fixed.

**Comment by ericmclachlan** [comment]
Awesome. It's weekend on my side of the world but I appreciate the quick turnaround. 👍

**Comment by ericmclachlan** [comment]
I just confirmed that my build seems to be working again. Thanks for sorting it out.
