### ISSUE TITLE
cannot install current version using pip

### ISSUE THREAD

**Issue by alex4747-pub** [google/pygtrie#33]
ayr@DESKTOP-DPGQQFH:/mnt/p/downloads$ pip install pygtrie
Collecting pygtrie
  Using cached https://files.pythonhosted.org/packages/3c/93/557455c974a21dd7ec0da309b9223952457c1999072bfe1f8f47f6091eab/pygtrie-2.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pygtrie.egg-info
    writing pip-egg-info/pygtrie.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pygtrie.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pygtrie.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pygtrie.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-EXlvog/pygtrie/setup.py", line 177, in <module>
        distutils.core.setup(**kwargs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/home/ayr/.local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python2.7/distutils/cmd.py", line 311, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
    TypeError: object() takes no parameters

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-EXlvog/pygtrie/
ayr@DESKTOP-DPGQQFH:/mnt/p/downloads$

**Comment by mina86** [comment]
This should now be fixed but you should consider migrating to Python 3.x. 2.x is EOL and I _will eventually_ stop caring about it.

**Comment by alex4747-pub** [comment]
Yes, fortunately it was easy to  convert my hobby code to python3.
